
package view.format;

import controlador.ConfiguracaoController;
import controlador.Funcoes;
import java.awt.Color;
import java.awt.HeadlessException;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import model.core.ConfiguracaoModel;
import view.core.AjudaView;

/*
 * @author jsilva
 */

public class EstatisticaView extends javax.swing.JFrame {

    Funcoes f = new Funcoes();
    ConfiguracaoModel configModel = new ConfiguracaoModel();
    ConfiguracaoController confController = new ConfiguracaoController();
    
    public EstatisticaView() {
        initComponents();
        carregarConfiguracao();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEstati = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaContagem = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnContar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblMediana = new javax.swing.JLabel();
        lblMedia = new javax.swing.JLabel();
        btnCopiar = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmiLimpar = new javax.swing.JMenuItem();
        jmiAjuda = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estatistica");

        txaContagem.setColumns(20);
        txaContagem.setRows(5);
        jScrollPane1.setViewportView(txaContagem);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancelar_32.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar (Esc)");
        btnCancelar.setMaximumSize(new java.awt.Dimension(70, 59));
        btnCancelar.setMinimumSize(new java.awt.Dimension(70, 59));
        btnCancelar.setPreferredSize(new java.awt.Dimension(70, 59));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Limpar_32.png"))); // NOI18N
        btnLimpar.setToolTipText("Limpar (F3)");
        btnLimpar.setMaximumSize(new java.awt.Dimension(70, 59));
        btnLimpar.setMinimumSize(new java.awt.Dimension(70, 59));
        btnLimpar.setPreferredSize(new java.awt.Dimension(70, 59));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnContar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Soma_32.png"))); // NOI18N
        btnContar.setToolTipText("Contar (F1)");
        btnContar.setMaximumSize(new java.awt.Dimension(70, 59));
        btnContar.setMinimumSize(new java.awt.Dimension(70, 59));
        btnContar.setPreferredSize(new java.awt.Dimension(70, 59));
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("0 registro");

        lblMediana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMediana.setForeground(new java.awt.Color(255, 255, 255));
        lblMediana.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMediana.setText("Mediana: 0");

        lblMedia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMedia.setForeground(new java.awt.Color(255, 255, 255));
        lblMedia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMedia.setText("Média: 0");

        btnCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Copiar_32.png"))); // NOI18N
        btnCopiar.setToolTipText("Copiar (F2)");
        btnCopiar.setMaximumSize(new java.awt.Dimension(70, 59));
        btnCopiar.setMinimumSize(new java.awt.Dimension(70, 59));
        btnCopiar.setPreferredSize(new java.awt.Dimension(70, 59));
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        panelEstati.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEstati.setLayer(btnCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEstati.setLayer(btnLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEstati.setLayer(btnContar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEstati.setLayer(lblTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEstati.setLayer(lblMediana, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEstati.setLayer(lblMedia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelEstati.setLayer(btnCopiar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelEstatiLayout = new javax.swing.GroupLayout(panelEstati);
        panelEstati.setLayout(panelEstatiLayout);
        panelEstatiLayout.setHorizontalGroup(
            panelEstatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstatiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelEstatiLayout.createSequentialGroup()
                        .addGroup(panelEstatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMediana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMedia, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addGroup(panelEstatiLayout.createSequentialGroup()
                                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addGap(13, 13, 13)))
                        .addGap(199, 199, 199)
                        .addComponent(btnContar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelEstatiLayout.setVerticalGroup(
            panelEstatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstatiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(panelEstatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnContar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstatiLayout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMediana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMedia)))
                .addContainerGap())
        );

        menuArquivo.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Contar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuArquivo.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem2.setText("Copiar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuArquivo.add(jMenuItem2);

        jmiLimpar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jmiLimpar.setText("Limpar");
        jmiLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLimparActionPerformed(evt);
            }
        });
        menuArquivo.add(jmiLimpar);

        jmiAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jmiAjuda.setText("Ajuda");
        jmiAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAjudaActionPerformed(evt);
            }
        });
        menuArquivo.add(jmiAjuda);

        jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        menuArquivo.add(jmiSair);

        menu.add(menuArquivo);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEstati)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEstati)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jmiLimparActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        dispose();
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        contar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
       contar();
    }//GEN-LAST:event_btnContarActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        copiar();
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        copiar();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAjudaActionPerformed
        AjudaView ajuda = new AjudaView(this, rootPaneCheckingEnabled, f.textoAjuda("CONTAGEM"));
    }//GEN-LAST:event_jmiAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstatisticaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstatisticaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstatisticaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstatisticaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstatisticaView().setVisible(true);
            }
        });
    }

    private void limpar(){
        txaContagem.setText("");
        lblTotal.setText("0 registro");
        lblMediana.setText("Mediana: 0");
        lblMedia.setText("Média: 0");
    }
    
    private void copiar(){
        if(!txaContagem.getText().equals("")){
            try {
                f.copiar(lblMediana.getText() + "\n" + lblMedia.getText());
                JOptionPane.showMessageDialog(this, "Dados copiados com sucesso!","Cópia",JOptionPane.INFORMATION_MESSAGE);
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, "Erro ao copiar dados" + e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
            }        
        }else{
            JOptionPane.showMessageDialog(this, "Não existem dados no campo estatístico!","Atenção",JOptionPane.WARNING_MESSAGE);
        }                
    }
    
    
    private void contar (){
        List <String> lista;// = new ArrayList();
        lista = f.gerarListaMediana(txaContagem.getText());
        
        lista = f.corrigirLista(lista);
        lista = f.ordernarLista(lista);                
        
        if(lista.size() > 1){
            lblTotal.setText(lista.size() + " registros");
        }else{
            lblTotal.setText(lista.size() + " registro");
        }
        
        
        int esquerda = 0;
        int direita = lista.size() -1;
        int meio = (esquerda + direita) / 2;
                
        float mediana = 0;
                
        if(lista.size()% 2 == 0){
            try {
                mediana = (Float.parseFloat (lista.get(meio)) + Float.parseFloat(lista.get(meio + 1)))/2 ;
            }catch (NumberFormatException  e) {                
                JOptionPane.showMessageDialog(this,"Erro ao efetuar cálculo (utilize apenas números)" + e.getMessage() , "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }else {
            mediana = Float.parseFloat(lista.get(meio));
        }
        DecimalFormat formato = new DecimalFormat("#.##");
        lblMediana.setText("Mediana: " + formato.format(mediana));
        lblMedia.setText("Média: " + f.calcularMedia(f.gerarListaPesquisa(txaContagem.getText())));                

        txaContagem.setText("");
        lista.forEach((dados)->{
            txaContagem.append(dados + "\n");
        });

    }
    
    private void carregarConfiguracao(){
        configModel = confController.validarConfig();        
        if((configModel.getTema().contains("FlatLight")) || (configModel.getTema().contains("Metal")) || (configModel.getTema().contains("FlatIntelliJ"))){
            lblMedia.setForeground(Color.black);
            lblMediana.setForeground(Color.black);
            lblTotal.setForeground(Color.black);
        }else{
            lblMedia.setForeground(Color.white);
            lblMediana.setForeground(Color.white);
            lblTotal.setForeground(Color.white);
        }
        this.panelEstati.updateUI();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContar;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmiAjuda;
    private javax.swing.JMenuItem jmiLimpar;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JLabel lblMedia;
    private javax.swing.JLabel lblMediana;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JDesktopPane panelEstati;
    private javax.swing.JTextArea txaContagem;
    // End of variables declaration//GEN-END:variables
}
